language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7-dev
before_install:
- pip install pytest pytest-cov
- pip install coveralls
script:
- stty size
- stty cols 80
- stty size
- pytest
after_success:
- coveralls
env:
- COLUMNS=80
deploy:
  provider: pypi
  user: sigvaldm
  on:
    tags: true
    python: 3.7-dev
  password:
    secure: 0rqOYEnF+nuWVHdcy7AHJUimRNZQNh/lSKNAlR/pmqRQ5GyOTV6b1A3Dujh9BNKDVzpa3px87Yr4gn3ESd0Um9kU3IDIZEpkaPAhFV0UaKfCU7tWWV3Zn2rDBFh8GfOzstaZaQjlkr5er0VAGGsDKg3Az0KT4KtEmUuNdRrrQGzgKTRbBbj1GKS7DlhOzPzhAQq3zhEd8MyqEheZmRHxVQZ5UqE9iBNAK9V8qPQTVNWvx7fwH0EmEyajB7LUURl5UORlx6PP29grnRD08vfo/kWPJdGXTTdjzkburXzphjtNQe6YDHTyKy6qykiNP4FBSuM19Kd3n6HJM6EoSjQCLiAcAzuM7F2Uzasud38TO52nxEbYmBV+fPFlaP1zdNvgH7CGgQTOW5NB6Rh4A9wIzJNOJCkkKDo1WushHDusYZKk5+E3t0yLFiT8AjzzUBcd3gAHOrzNHyVvomQSZ8dCnOvs3HBIXiizCIvQ+D/yJyagDvlgA8gsc2JIQsSTIhh9eiwBIRjmyfg27qbg/bzLu6qHbRLX8e33Zj9zCKorknpRwCokLQucJO7wGJZCBY4MxbqYWa4Xdly0r1V8XKrR8yiBtSg1BLzsrT2C4CBWP1ABqzbu3uiWZ44sSf79DekDnGtnq9x+VTIOGp47OI1gvVmjrtipz7oXgWPPzXFTVjM=
